FROM node:alpine

MAINTAINER Jonathan Baraldi

RUN mkdir -p /src 

WORKDIR /src
ADD . /src

EXPOSE  8080

CMD ["node", "/src/index.js"]


#This code sets up an environment to run a Node.js application. It will create a directory called "src" in which the application will be stored, add the application files to the directory, expose port 8080, and run the application using the index.js file.